import streamlit as st
import pandas as pd
import joblib
import plotly.express as px
import os
import requests
from pathlib import Path
from datetime import datetime

# =============================================================================
# Streamlit Page Config
# =============================================================================
st.set_page_config(
    page_title="Failure Probability",
    layout="wide"
)

st.session_state.update({"__streamlit_page_name__": "Failure Probability"})

# =============================================================================
# Config
# =============================================================================
HUGGINGFACE_URL = "https://huggingface.co/louislb1302/failure_model.joblib/resolve/main/failure_model.joblib"
LOCAL_MODEL_PATH = Path("failure_model.joblib")
DATA_PATH = Path("data/yarra_assets_unknown.csv")

# =============================================================================
# Helper: Download model from Hugging Face
# =============================================================================
@st.cache_resource
def download_model_from_hf(url, local_path):
    """Download model from Hugging Face if not available locally."""
    if not local_path.exists():
        st.write("Downloading the failure prediction model from Hugging Face...")
        response = requests.get(url, stream=True)

        if response.status_code == 200:
            with open(local_path, "wb") as f:
                for chunk in response.iter_content(chunk_size=8192):
                    if chunk:
                        f.write(chunk)
            size_mb = os.path.getsize(local_path) / (1024 * 1024)
            st.write(f"Model successfully downloaded ({size_mb:.2f} MB)")
        else:
            st.error(f"Error downloading model: HTTP {response.status_code}")
            st.stop()

    return joblib.load(local_path)

# =============================================================================
# Load Dataset
# =============================================================================
@st.cache_data
def load_assets():
    """Load the raw dataset."""
    return pd.read_csv(DATA_PATH)

# =============================================================================
# Preprocess for Prediction
# =============================================================================
def preprocess_for_prediction(df):
    """
    Prepare the dataset for failure probability prediction.
    Adds computed features like 'age'.
    """
    current_year = datetime.now().year

    # Compute 'age' if missing
    if "age" not in df.columns:
        df["age"] = current_year - df["installation_year"]

    return df

# =============================================================================
# Generate Failure Predictions
# =============================================================================
def predict_failure(df, model):
    """
    Use the trained model to predict failure probabilities
    and add them to the dataframe as 'Failure_Prob'.
    """
    feature_cols = [
        "asset_name", "asset_type", "material", "diameter",
        "installation_year", "status", "network_type",
        "length", "depth", "zone", "pressure_rating",
        "location", "age"
    ]

    # Check for missing columns
    missing_cols = [col for col in feature_cols if col not in df.columns]
    if missing_cols:
        st.error(f"Missing required columns for failure prediction: {missing_cols}")
        return df

    # Predict probabilities
    X = df[feature_cols]
    df["Failure_Prob"] = model.predict_proba(X)[:, 1]

    return df

# =============================================================================
# Load Model
# =============================================================================
@st.cache_resource
def load_model():
    return download_model_from_hf(HUGGINGFACE_URL, LOCAL_MODEL_PATH)

# =============================================================================
# Streamlit Layout
# =============================================================================
st.title("Asset Failure Probability Dashboard")
st.markdown("""
This dashboard **predicts the probability of failure** for each water infrastructure asset.  
The predictions help prioritize **preventive maintenance**, reduce emergency repairs, and guide investment planning.

The data shown comes from `yarra_assets_unknown.csv` and the **failure probabilities** are generated by a trained model.
""")

# ---- Load data and model ----
df = load_assets()
df = preprocess_for_prediction(df)
model = load_model()

# ---- Generate failure predictions ----
df = predict_failure(df, model)

# =============================================================================
# Sidebar Filters
# =============================================================================
st.sidebar.header("Filters")

zones = st.sidebar.multiselect(
    "Zone",
    options=df["zone"].unique(),
    default=df["zone"].unique()
)

types = st.sidebar.multiselect(
    "Asset Type",
    options=df["asset_type"].unique(),
    default=df["asset_type"].unique()
)

min_failure = float(df["Failure_Prob"].min())
max_failure = float(df["Failure_Prob"].max())

failure_range = st.sidebar.slider(
    "Filter by Failure Probability",
    min_value=min_failure,
    max_value=max_failure,
    value=(min_failure, max_failure),
    step=0.01
)

# ---- Filter dataframe ----
filtered_df = df[
    (df["zone"].isin(zones)) &
    (df["asset_type"].isin(types)) &
    (df["Failure_Prob"].between(failure_range[0], failure_range[1]))
]

# =============================================================================
# KPIs
# =============================================================================
st.subheader("Key Metrics")
col1, col2 = st.columns(2)
col1.metric("Total Assets", len(filtered_df))
col2.metric("Average Failure Probability", f"{filtered_df['Failure_Prob'].mean():.2f}")

# =============================================================================
# Top 5 Assets with Highest Failure Probability
# =============================================================================
st.subheader("Top 5 Assets with Highest Failure Probability")

top_5 = filtered_df.sort_values(by="Failure_Prob", ascending=False).head(5)
st.table(top_5[["asset_id", "asset_type", "material", "Failure_Prob", "zone", "status"]])

st.markdown("""
These assets should be **prioritized for preventive maintenance** or **immediate inspection** due to their high risk of failure.
""")

# =============================================================================
# Map Visualization
# =============================================================================
st.subheader("Geospatial View of Assets by Failure Probability")

# Split geometry into lat/lon
coords = filtered_df["geometry"].str.split(",", expand=True).astype(float)
filtered_df["lat"] = coords[0]
filtered_df["lon"] = coords[1]

map_fig = px.scatter_mapbox(
    filtered_df,
    lat="lat",
    lon="lon",
    color="Failure_Prob",
    hover_data=["asset_id", "asset_type", "material", "Failure_Prob"],
    color_continuous_scale="Reds",
    title="Failure Probability by Location",
    zoom=10
)
map_fig.update_layout(mapbox_style="open-street-map")
st.plotly_chart(map_fig, use_container_width=True)

# =============================================================================
# Full Table
# =============================================================================
st.subheader("Detailed Asset Table")
st.dataframe(
    filtered_df[
        [
            "asset_id", "asset_name", "asset_type", "material",
            "installation_year", "Failure_Prob", "zone", "status", "location", "age"
        ]
    ].sort_values("Failure_Prob", ascending=False),
    use_container_width=True
)

# =============================================================================
# Histogram of Failure Probability
# =============================================================================
st.subheader("Failure Probability Distribution")

hist_fig = px.histogram(
    filtered_df,
    x="Failure_Prob",
    nbins=20,
    title="Distribution of Failure Probabilities",
    labels={"Failure_Prob": "Failure Probability"}
)
st.plotly_chart(hist_fig, use_container_width=True)

st.markdown("""
Assets with a **high probability of failure** should be inspected and scheduled for **preventive maintenance** to avoid costly breakdowns.
""")
